"""initial schema

Revision ID: 0d9812d8981f
Revises: 
Create Date: 2026-07-03 16:54:25.606154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9812d8981f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_CALIBRATION', 'OUT_OF_SERVICE', name='equipmentstatus'), nullable=True),
    sa.Column('last_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('next_calibration_due', sa.DateTime(), nullable=True),
    sa.Column('calibration_certificate', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('product_grades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_type', sa.Enum('CRUDE_OIL', 'GASOLINE', 'GASOIL', 'KEROSENE', 'JET_FUEL', 'FUEL_OIL', 'NAPHTHA', 'LPG', 'BITUMEN', 'LUBE_OIL', 'OTHER', name='producttype'), nullable=False),
    sa.Column('standard_reference', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'REVIEWER', 'APPROVER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_type', sa.Enum('CRUDE_OIL', 'GASOLINE', 'GASOIL', 'KEROSENE', 'JET_FUEL', 'FUEL_OIL', 'NAPHTHA', 'LPG', 'BITUMEN', 'LUBE_OIL', 'OTHER', name='producttype'), nullable=True),
    sa.Column('product_grade_id', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('sampling_point', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sampling_datetime', sa.DateTime(), nullable=True),
    sa.Column('sampled_by', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('condition_on_receipt', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_TESTING', 'COMPLETED', 'ARCHIVED', 'REJECTED', name='samplestatus'), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_grade_id'], ['product_grades.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_sample_code'), ['sample_code'], unique=True)

    op.create_table('test_methods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('standard_ref', sa.String(), nullable=True),
    sa.Column('sop_reference', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('measurement_uncertainty', sa.Float(), nullable=True),
    sa.Column('accredited', sa.Boolean(), nullable=True),
    sa.Column('default_equipment_id', sa.String(), nullable=True),
    sa.Column('spec_min', sa.Float(), nullable=True),
    sa.Column('spec_max', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('deviations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raised_by', sa.String(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_grade_id', sa.String(), nullable=False),
    sa.Column('test_method_id', sa.String(), nullable=False),
    sa.Column('spec_type', sa.Enum('MIN', 'MAX', 'RANGE', 'INFORMATIVE', name='spectype'), nullable=False),
    sa.Column('spec_min', sa.Float(), nullable=True),
    sa.Column('spec_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('decision_rule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_grade_id'], ['product_grades.id'], ),
    sa.ForeignKeyConstraint(['test_method_id'], ['test_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_grade_id', 'test_method_id', name='uq_grade_method')
    )
    op.create_table('test_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('test_method_id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESULT_ENTERED', 'REVIEWED', 'APPROVED', name='testassignmentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['test_method_id'], ['test_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('measurement_uncertainty', sa.Float(), nullable=True),
    sa.Column('applied_spec_min', sa.Float(), nullable=True),
    sa.Column('applied_spec_max', sa.Float(), nullable=True),
    sa.Column('conformity', sa.Enum('CONFORM', 'NONCONFORM', 'CONDITIONAL', 'NOT_EVALUATED', name='conformitystatus'), nullable=True),
    sa.Column('tested_by', sa.String(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['test_assignments.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('test_assignments')
    op.drop_table('specifications')
    op.drop_table('deviations')
    op.drop_table('test_methods')
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_sample_code'))

    op.drop_table('samples')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('product_grades')
    op.drop_table('equipment')
    # ### end Alembic commands ###
